name: Deploy to Production

on:
  push:
    branches:
      - main  # Set your main branch here, adjust if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Replace with yarn if you use yarn

      - name: Build
        run: npm run build  # Replace with your build script if different

      - name: Deploy to Firebase Hosting  # Adjust based on your hosting service
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting

      # Add more steps here if you need to deploy to a different service

